name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push API
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfiles/aspnetcore8.0-NodeJS.dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/aspnet:8.0
